
# Setup
title: Senior Software Developer
tagline: Web & Mobile Development Portfolio
url: https://preview--cv-portfolio-hub.lovable.app/
paginate: 4
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Author
author:
  name: Shannon Lockett
  url: https://github.com/shazzar00ni
  email: shannon.lockett@example.com

# Custom vars
version: 3.0.0
